name: Sync to AUR

on:
  workflow_dispatch:
  push:
    branches:
      - vicinae
      - vicinae-appimage-bin
      - vicinae-bin
      - vicinae-git
    paths:
      - .SRCINFO

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Setup SSH
        env:
          AUR_SSH_KEY: "${{ secrets.AUR_SSH_KEY }}"
          AUR_SSH_KEY_PUB: "${{ secrets.AUR_SSH_KEY_PUB }}"
        run: |
          mkdir -p ~/.ssh

          echo "$AUR_SSH_KEY" > ~/.ssh/aur
          echo "$AUR_SSH_KEY_PUB" > ~/.ssh/aur.pub
          chmod 600 ~/.ssh/aur

          cp .github/ssh_config ~/.ssh/config
          chmod 600 ~/.ssh/config

      - name: Sync to AUR
        run: bash .github/scripts/sync-to-aur.sh --push
